version: "3"

services:
  telegraf:
    image: telegraf:1.11-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      # - /var/run/utmp:/var/run/utmp:ro
    environment:
      - TZ=Asia/Macau
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_MOUNT_PREFIX=/hostfs
    network_mode: host
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.7-alpine
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/influxdb:/var/lib/influxdb
    # 环境变量配置: https://docs.influxdata.com/influxdb/v1.7/administration/config/#influxdb-environment-variables-influxdb
    environment:
      - INFLUXDB_DB=gen
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - TZ=Asia/Macau
    restart: always
    ports:
      - "8086:8086"
  chronograf:
    image: chronograf
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/chronograf:/var/lib/chronograf
    # 环境变量配置: https://docs.influxdata.com/chronograf/v1.7/administration/config-options
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
      - KAPACITOR_URL=http://kapacitor:9092
      - TZ=Asia/Macau
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
  kapacitor:
    image: kapacitor
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=admin
      - KAPACITOR_INFLUXDB_0_PASSWORD=admin
      - TZ=Asia/Macau
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/kapacitor:/var/lib/kapacitor
    # volumes:
    # - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    ports:
      - "9092:9092"
    restart: always
    depends_on:
      - influxdb
